package com.example.myapplication.util

import com.example.myapplication.data.remote.dto.market.RegularMarketPrice
import com.example.myapplication.data.remote.dto.market.RegularMarketTime

val sampleMarketData = listOf(
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CME",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Chicago Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        shortName = "S&P Futures",
        sourceInterval = 10,
        symbol = "ES=F",
        triggerable = false,
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "NYM",
        exchangeDataDelayedBy = 15,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "New York Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        shortName = "Crude Oil Futures",
        sourceInterval = 15,
        symbol = "CL=F",
        triggerable = false,
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CBT",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/Chicago",
        exchangeTimezoneShortName = "CDT",
        fullExchangeName = "Chicago Board of Trade",
        gmtOffSetMilliseconds = -18000000,
        language = "en-US",
        market = "us24_market",
        marketState = "PRE",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Corn Futures",
        sourceInterval = 10,
        symbol = "ZC=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CME",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Chicago Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Nasdaq Futures",
        sourceInterval = 10,
        symbol = "NQ=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "NYM",
        exchangeDataDelayedBy = 15,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "New York Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Gold Futures",
        sourceInterval = 15,
        symbol = "GC=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CME",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Chicago Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "POST",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Dow Futures",
        sourceInterval = 10,
        symbol = "YM=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CBT",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/Chicago",
        exchangeTimezoneShortName = "CDT",
        fullExchangeName = "Chicago Board of Trade",
        gmtOffSetMilliseconds = -18000000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Soybean Futures",
        sourceInterval = 10,
        symbol = "ZS=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "NYM",
        exchangeDataDelayedBy = 15,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "New York Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Natural Gas Futures",
        sourceInterval = 15,
        symbol = "NG=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CME",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Chicago Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Euro FX Futures",
        sourceInterval = 10,
        symbol = "6E=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "ICE",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Intercontinental Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Cotton Futures",
        sourceInterval = 10,
        symbol = "CT=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CME",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Chicago Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "PRE",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Live Cattle Futures",
        sourceInterval = 10,
        symbol = "LE=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "NYM",
        exchangeDataDelayedBy = 15,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "New York Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Silver Futures",
        sourceInterval = 15,
        symbol = "SI=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CBT",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/Chicago",
        exchangeTimezoneShortName = "CDT",
        fullExchangeName = "Chicago Board of Trade",
        gmtOffSetMilliseconds = -18000000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Wheat Futures",
        sourceInterval = 10,
        symbol = "ZW=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "CME",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Chicago Mercantile Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Australian Dollar Futures",
        sourceInterval = 10,
        symbol = "6A=F",
        triggerable = false
    ),
    com.example.myapplication.domain.marketSummary.model.Result(
        exchange = "ICE",
        exchangeDataDelayedBy = 10,
        exchangeTimezoneName = "America/New_York",
        exchangeTimezoneShortName = "EDT",
        fullExchangeName = "Intercontinental Exchange",
        gmtOffSetMilliseconds = -14400000,
        language = "en-US",
        market = "us24_market",
        marketState = "REGULAR",
        priceHint = 2,
        quoteType = "FUTURE",
        region = "US",
        regularMarketPrice = RegularMarketPrice("435.75", 435.75),
        regularMarketTime = RegularMarketTime("12:25AM CDT", 4234),
        shortName = "Sugar Futures",
        sourceInterval = 10,
        symbol = "SB=F",
        triggerable = false
    )
)